__author__ = 'hanley'
from collections import OrderedDict

colorlist = OrderedDict([
("background"  ,  "rgb(229, 225, 214)"),
("background_top"  ,  "rgb( 83,  82,  78)"),
("background_top_gradient"  ,  "rgb(127, 127, 127)"),
("content_background"  ,  "white"),
("content_border_gradient1"  ,  "rgb(201, 198, 188)"),
("content_border_gradient2"  ,  "rgb(174, 171, 163)"),
("content_text"  ,  "black"),
("header_background"  ,  "PRIMARY_COLOR"),
("headings"  ,  "PRIMARY_COLOR"),
("topmenu_text"  ,  "white"),
("dropdownmenu_background"  ,  "rgb(241, 241, 241)"),
("dropdownmenu_text"  ,  "SECONDARY_COLOR"),
("dropdownmenu_separator"  ,  "rgb(230, 230, 230)"),
("menu_text"  ,  "white"),
("messages"  ,  "rgb(255, 221,  63)"),
("messages_text"  ,  "black"),
("basket_background"  ,  "rgb(247, 247, 247)"),
("basket_text"  ,  "PRIMARY_COLOR"),
("facet"  ,  "lightgrey"),
("facet_text"  ,  "black"),
("facet_active"  ,  "PRIMARY_COLOR"),
("facet_active_text"  ,  "white"),
("borders"  ,  "lightgrey"),
("shaded_background"  ,  "rgb(247, 247, 247)"),
("tag"  ,  "PRIMARY_COLOR"),
("tag_text"  ,  "white"),
("tag_secondary"  ,  "lightgrey"),
("tag_secondary_text"  ,  "black"),
("links"  ,  "SECONDARY_COLOR"),
("user_icons"  ,  "PRIMARY_COLOR"),
("other_user_icons"  ,  "white"),
("js_warning_text"  ,  "white"),
("js_warning_background"  ,  "red"),
("permissions_allowed"  ,  "green"),
("permissions_denied"  ,  "red"),
("permissions_unset"  ,  "lightgrey"),
("success"  ,  "green"),
("fail"  ,  "red"),
("drop_shadow"  ,  "grey")  ])

for key, value in colorlist.items():
    print "$%s :  %s " % (key, value)